[package]
name = "basics"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "variables"
path = "src/bin/variables.rs"

[[bin]]
name = "data_types"
path = "src/bin/data_types.rs"

[[bin]]
name = "functions"
path = "src/bin/functions.rs"

[[bin]]
name = "conditionals"
path = "src/bin/conditionals.rs"

[[bin]]
name = "shadowing"
path = "src/bin/shadowing.rs"


[[bin]]
name = "basic_loops"
path = "src/bin/basic_loops.rs"